apiVersion: v1
kind: Service
metadata:
  name: congressus-app
  namespace: anvt
spec:
  type: NodePort
  selector:
    app: congressus-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
